Repository nervosnetwork/ckb-sdk-js, pull requests merged in 2019-05, with the labels that each got.

#136 [ᚬrc/v0.11.0] Add address package
  .travis.yml
  packages/ckb-sdk-address/README.md
  packages/ckb-sdk-address/__tests__/ckb-sdk-address.test.js
  packages/ckb-sdk-address/package.json
  packages/ckb-sdk-address/src/index.ts
  packages/ckb-sdk-address/tsconfig.json
Labels: enhancement

#155 [ᚬrc/v0.11.0] Document
  .travis.yml
  README.md
  package.json
Labels: hotfix

#156 [ᚬrc/v0.11.0] docs: fix typo from 'beck32Address' to 'bech32Address' in the readme
  README.md
Labels: hotfix

#162 [ᚬrc/v0.11.0] docs: fix typo in readme and type comments
  README.md
  packages/ckb-types/index.d.ts
Labels: hotfix

#171 [ᚬrc/v0.11.0] docs: fix typos
  README.md
Labels: hotfix

#169 Set all number to string in types
  README.md
  lerna.json
  packages/ckb-cli/package.json
  packages/ckb-sdk-address/package.json
  packages/ckb-sdk-core/package.json
  packages/ckb-sdk-rpc/__tests__/formatters/fixtures.json
  packages/ckb-sdk-rpc/package.json
  packages/ckb-sdk-rpc/src/paramsFormatter.ts
  packages/ckb-sdk-rpc/src/resultFormatter.ts
  packages/ckb-sdk-rpc/types/CKB_RPC/index.d.ts
  packages/ckb-sdk-utils/__tests__/ckb-utils.test.js
  packages/ckb-sdk-utils/package.json
  packages/ckb-sdk-utils/src/index.ts
  packages/ckb-types/index.d.ts
  packages/ckb-types/package.json
Labels: Next

#172 feat(rpc): update result of dryRunTransaction from hash to { cycles }
  packages/ckb-sdk-rpc/src/defaultRPC.ts
  packages/ckb-types/index.d.ts
Labels: Next

#173 [ᚬrc/v0.11.0] docs: add basic descriptions to all modules except the wallet module, …
  README.md
  packages/ckb-cli/README.md
  packages/ckb-cli/package.json
  packages/ckb-sdk-address/README.md
  packages/ckb-sdk-address/package.json
  packages/ckb-sdk-core/README.md
  packages/ckb-sdk-core/package.json
  packages/ckb-sdk-rpc/README.md
  packages/ckb-sdk-rpc/package.json
  packages/ckb-sdk-utils/README.md
  packages/ckb-sdk-utils/package.json
  packages/ckb-types/README.md
  packages/ckb-types/package.json
Labels: hotfix

#202 [ᚬmaster] Rc/v0.12.0
  .eslintrc.js
  CHANGELOG.md
  README.md
  lerna.json
  packages/ckb-cli/CHANGELOG.md
  packages/ckb-cli/package.json
  packages/ckb-sdk-address/CHANGELOG.md
  packages/ckb-sdk-address/__tests__/ckb-sdk-address.test.js
  packages/ckb-sdk-address/package.json
  packages/ckb-sdk-core/CHANGELOG.md
  packages/ckb-sdk-core/__tests__/ckb-core.test.js
  packages/ckb-sdk-core/examples/sendTransaction.js
  packages/ckb-sdk-core/package.json
  packages/ckb-sdk-core/src/index.ts
  packages/ckb-sdk-rpc/CHANGELOG.md
  packages/ckb-sdk-rpc/__tests__/ckb-rpc-helpers.js
  packages/ckb-sdk-rpc/__tests__/ckb-rpc.test.js
  packages/ckb-sdk-rpc/__tests__/formatters/fixtures.json
  packages/ckb-sdk-rpc/__tests__/formatters/params.test.js
  packages/ckb-sdk-rpc/__tests__/formatters/result.test.js
  packages/ckb-sdk-rpc/package.json
  packages/ckb-sdk-rpc/src/defaultRPC.ts
  packages/ckb-sdk-rpc/src/index.ts
  packages/ckb-sdk-rpc/src/method.ts
  packages/ckb-sdk-rpc/src/paramsFormatter.ts
  packages/ckb-sdk-rpc/src/resultFormatter.ts
  packages/ckb-sdk-rpc/types/CKB_RPC/index.d.ts
  packages/ckb-sdk-utils/CHANGELOG.md
  packages/ckb-sdk-utils/__tests__/ckb-utils.test.js
  packages/ckb-sdk-utils/__tests__/ecpair.test.js
  packages/ckb-sdk-utils/__tests__/signature-fixtures.json
  packages/ckb-sdk-utils/package.json
  packages/ckb-sdk-utils/src/ecpair.ts
  packages/ckb-sdk-utils/tsconfig.json
  packages/ckb-sdk-wallet/CHANGELOG.md
  packages/ckb-sdk-wallet/README.md
  packages/ckb-sdk-wallet/__tests__/ckb-wallet.test.js
  packages/ckb-sdk-wallet/package.json
  packages/ckb-sdk-wallet/src/account.ts
  packages/ckb-sdk-wallet/src/index.ts
  packages/ckb-sdk-wallet/tsconfig.json
  packages/ckb-types/CHANGELOG.md
  packages/ckb-types/index.d.ts
  packages/ckb-types/package.json
  yarn.lock
Labels: breaking change
